//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Service.User.Persistance.Repositories.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Service.User.Persistance.Repositories.User.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete Users
        ///output
        ///	DELETED.*
        ///where UserGuid = @UserGuid.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from Users
        ///where
        ///	Email = @Email.
        /// </summary>
        internal static string GET_BY_EMAIL {
            get {
                return ResourceManager.GetString("GET_BY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from Users
        ///where
        ///	Email = @Email
        ///	and Password = @Password.
        /// </summary>
        internal static string GET_BY_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("GET_BY_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from Users
        ///where
        ///	UserGuid = @UserGuid.
        /// </summary>
        internal static string GET_BY_USER_GUID {
            get {
                return ResourceManager.GetString("GET_BY_USER_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Users
        ///(
        ///	[UserGuid],
        ///	[Email],
        ///	[Password], 
        ///	[FirstName], 
        ///    [LastName], 
        ///    [DateCreated], 
        ///    [DateUpdated]
        ///)
        ///output
        ///	INSERTED.*
        ///values
        ///(
        ///	@UserGuid,
        ///	@Email, 
        ///	@Password, 
        ///	@FirstName, 
        ///    @LastName,
        ///	GETDATE(),
        ///	GETDATE()
        ///).
        /// </summary>
        internal static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Users
        ///set
        ///	FirstName = @FirstName,
        ///	LastName = @LastName,
        ///	DateUpdated = GETDATE()
        ///output
        ///	INSERTED.*
        ///where UserGuid = @UserGuid.
        /// </summary>
        internal static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
    }
}
